name: pyinstaller
on:
  push:
    branches: ["main"]
    paths-ignore:
      - .*
      - .*/**
      - demos/**
      - docs/**
      - .git*
      - CONTRIBUTING.md
      - LICENSE
      - README.md
      - "!.github/workflows/pyinstaller.yml"
  pull_request:
    paths-ignore:
      - .*
      - .*/**
      - demos/**
      - docs/**
      - .git*
      - CONTRIBUTING.md
      - LICENSE
      - README.md
      - "!.github/workflows/pyinstaller.yml"
  workflow_call:
concurrency:
  # When run via `workflow_call` the `github.workflow` and `github.ref` are the
  # same as the parent so we need a differentiation suffix.
  group: ${{ github.workflow }}-${{ github.ref }}-pyinstaller
  cancel-in-progress: true
jobs:
  pyinstaller:
    strategy:
      fail-fast: false
      matrix:
        include:
          # https://packaging.python.org/en/latest/specifications/platform-compatibility-tags/#platform-tag
          # target=$(python -c 'import sysconfig; print(sysconfig.get_platform().replace("-", "_"))')
          - { os: ubuntu-latest, target: linux_x86_64 }
          - { os: macos-latest, target: macosx_10.9_universal2 }
          - { os: windows-latest, target: win_amd64 }
    defaults:
      run:
        shell: bash
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: pip
      # TODO: Use pipenv
      - run: pip install -e .
      - run: pip install pyinstaller
      - run: bikeshed update
      - run: pyinstaller -y --collect-all=bikeshed --name=bikeshed ./bikeshed.py
      - uses: actions/upload-artifact@v4
        with:
          name: bikeshed-${{ matrix.target }}
          path: dist/bikeshed
